// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuvhazgtfqaoriwzfkdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51dmhhemd0ZnFhb3Jpd3pma2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMTk4MjksImV4cCI6MjA3Njg5NTgyOX0.nzFwWZJcnffmRQGr162uzHQyg12DvdFCH_-6FdGXblo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});